BEGIN;

ALTER TABLE role_menu
    ADD COLUMN IF NOT EXISTS site_id BIGINT;

ALTER TABLE role_menu DROP CONSTRAINT IF EXISTS role_menu_pkey;

ALTER TABLE role_menu
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE role_menu
    ADD CONSTRAINT role_menu_pkey PRIMARY KEY (id);

ALTER TABLE role_menu
    ALTER COLUMN role_id SET NOT NULL,
    ALTER COLUMN menu_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_role_menu_role_menu_common
    ON role_menu (role_id, menu_id)
    WHERE site_id IS NULL AND is_deleted = false;

CREATE UNIQUE INDEX IF NOT EXISTS uq_role_menu_role_menu_site
    ON role_menu (role_id, menu_id, site_id)
    WHERE site_id IS NOT NULL AND is_deleted = false;

CREATE INDEX IF NOT EXISTS idx_role_menu_role_site
    ON role_menu (role_id, site_id);

CREATE INDEX IF NOT EXISTS idx_role_menu_menu_site
    ON role_menu (menu_id, site_id);

COMMIT;
