CREATE TABLE IF NOT EXISTS server_resource_metric (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_name VARCHAR(20)   NOT NULL,
    cpu_percent  NUMERIC(6, 2) NOT NULL,
    memory_mb    NUMERIC(10, 2) NOT NULL,
    captured_at  TIMESTAMPTZ   NOT NULL
);

CREATE INDEX IF NOT EXISTS server_resource_metric_process_captured_idx
    ON server_resource_metric (process_name, captured_at);
