-- FO 트레이닝 세션 등록(리드 캡처) 테이블 DDL
-- 진입 API: POST /api/v1/fo/training/registrations (TrainingRegistrationController)
-- Entity: com.ge.bo.entity.TrainingRegistration
--
-- 실행 안내
--  * developer/local 프로파일은 spring.jpa.hibernate.ddl-auto=update 이므로 bo-api 재기동 시
--    Entity 기준으로 training_registration 테이블/인덱스가 자동 생성된다(단, FK 제약은 자동 생성되지 않음).
--  * 아래 스크립트를 먼저 1회 실행하면 사용자 승인 DDL(FK 포함)이 그대로 반영된다.
--  * 이미 자동 생성된 뒤라도 FK 블록만 별도로 실행하면 참조 무결성을 보강할 수 있다.

CREATE TABLE IF NOT EXISTS training_registration (
    id                    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id         BIGINT        NOT NULL,
    session_id            BIGINT        NOT NULL,
    student_name          VARCHAR(100)  NOT NULL,
    email                 VARCHAR(255)  NOT NULL,
    job_title             VARCHAR(100)  NOT NULL,
    phone                 VARCHAR(20)   NOT NULL,
    company_name          VARCHAR(100)  NOT NULL,
    event_date            DATE          NOT NULL,
    street_address        VARCHAR(255),
    address2              VARCHAR(255),
    apartment             VARCHAR(100),
    city                  VARCHAR(100),
    state_province        VARCHAR(100),
    zip_code              VARCHAR(20),
    type_of_business      VARCHAR(30),
    privacy_consent_flag  BOOLEAN       NOT NULL,
    created_ip            VARCHAR(50),
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 외래키 (page_data 참조). 이미 존재하면 무시.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'training_registration_curriculum_id_fk') THEN
        ALTER TABLE training_registration
            ADD CONSTRAINT training_registration_curriculum_id_fk
            FOREIGN KEY (curriculum_id) REFERENCES page_data(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'training_registration_session_id_fk') THEN
        ALTER TABLE training_registration
            ADD CONSTRAINT training_registration_session_id_fk
            FOREIGN KEY (session_id) REFERENCES page_data(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS training_registration_email_idx      ON training_registration (email);
CREATE INDEX IF NOT EXISTS training_registration_created_at_idx ON training_registration (created_at);

COMMENT ON TABLE  training_registration IS 'FO 트레이닝 세션 등록(리드 캡처) 저장(이력성 append-only)';
COMMENT ON COLUMN training_registration.type_of_business IS '공통코드 BUSINESSTYPE 코드값(001=Rep/002=Distributor/003=End User)';
