-- FO Training Request(비정기 교육 신청, Step1~4) 테이블 DDL
-- 진입 API: POST /api/v1/fo/training/requests (FoTrainingController)
-- Entity: com.ge.bo.entity.TrainingRequest
--
-- 실행 안내
--  * developer/local 프로파일은 spring.jpa.hibernate.ddl-auto=update 이므로 bo-api 재기동 시
--    Entity 기준으로 training_request 테이블/인덱스가 자동 생성된다.
--  * dev/prod 프로파일은 자동 생성되지 않으므로 아래 스크립트를 1회 실행해야 한다.

CREATE TABLE IF NOT EXISTS training_request (
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Step1: Basic Information
    training_track          VARCHAR(50),
    first_name              VARCHAR(200)  NOT NULL,
    last_name               VARCHAR(200),
    company                 VARCHAR(200)  NOT NULL,
    street_address          VARCHAR(255)  NOT NULL,
    address2                VARCHAR(255),
    city                    VARCHAR(100)  NOT NULL,
    state                   VARCHAR(100)  NOT NULL,
    zip                     VARCHAR(20)   NOT NULL,
    phone                   VARCHAR(20)   NOT NULL,
    email                   VARCHAR(255)  NOT NULL,
    title                   VARCHAR(200),
    cell_phone              VARCHAR(20),
    sales_contact           VARCHAR(20),
    -- Step2: Requested Date(s) of Training
    session_count           VARCHAR(200)  NOT NULL,
    session_days            VARCHAR(20)   NOT NULL,
    schedule_start          DATE          NOT NULL,
    schedule_end            DATE          NOT NULL,
    student_count           VARCHAR(20)   NOT NULL,
    -- Step3: Training Class Location
    -- ※ location_* / contact_* 는 In-Person 일 때만 입력되는 값이라 nullable (Virtual 이면 전부 비어 있음)
    training_format         VARCHAR(20)   NOT NULL,
    location_name           VARCHAR(200),
    location_street_address VARCHAR(255),
    location_address2       VARCHAR(255),
    location_city           VARCHAR(100),
    location_state          VARCHAR(100),
    location_zip            VARCHAR(20),
    contact_person          VARCHAR(50),
    contact_details         VARCHAR(400),
    -- Step4: Training Class Details
    selected_products       JSONB         NOT NULL,
    job_titles              JSONB,
    student_involvement     JSONB,
    vfd_understanding       VARCHAR(10),
    vfd_understanding_topics JSONB,
    comments                TEXT,
    consent_checked         BOOLEAN       NOT NULL,
    -- 감사
    created_ip              VARCHAR(50),
    created_at              TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS training_request_email_idx      ON training_request (email);
CREATE INDEX IF NOT EXISTS training_request_created_at_idx ON training_request (created_at);

COMMENT ON TABLE  training_request IS 'FO Training Request(비정기 교육 신청) 저장(이력성 append-only)';
COMMENT ON COLUMN training_request.selected_products IS 'Step4 선택 제품 목록 JSON 배열 [{id,name,type,groupId,groupTitle}]';
COMMENT ON COLUMN training_request.vfd_understanding IS 'VFD 이해도 질문 응답(Yes/No, VFD 제품 선택 시에만 노출)';
